name: Energie Update (Debug)

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Show working directory
        run: pwd

      - name: List files before script
        run: ls -l

      - name: Run script
        run: python energie_script.py

      - name: Show energie.json content
        run: cat energie.json || echo "Datei nicht gefunden"

      - name: Show git diff
        run: git diff energie.json || echo "Keine Unterschiede"

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Andreasadac/energie-daten.git
          git add energie.json
          git commit -m "Update energie.json" || echo "Keine Änderungen zum Commit"
          git push origin HEAD:${{ github.ref }} || echo "Push fehlgeschlagen"
