name: Energie Update mit Fallback

on:
  schedule:
    - cron: '0 11 * * *'  # Läuft täglich um 11:00 Uhr
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run energie_script.py mit Fallback
        run: python energie_script.py

      - name: Zeige Inhalt von energie.json
        run: cat energie.json || echo "Datei nicht gefunden"

      - name: Zeige Unterschiede zur vorherigen Version
        run: git diff energie.json || echo "Keine Unterschiede"

      - name: Commit und Push Änderungen
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/Andreasadac/energie-daten.git
          git add energie.json
          git commit -m "Update energie.json (mit Fallback)" || echo "Keine Änderungen zum Commit"
          git push origin HEAD:${{ github.ref }} || echo "Push fehlgeschlagen"
